# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 387187401032f0c66c9467595f34e43506d26e990db3376bce44059fce19846a30806105ac391ab6d41e90da3b77f744c7ea785b0e6636f56874f26514abae35

test:
  secret_key_base: 03bdd2ab8be31f3a2d1c10067eb06a66e5ef764f0d1e4c8467624ca7c5e5a16504a185de7c685c0ee94b1a15071d4572da6f31f9422cdbc7354ce2324ebeeb20

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
